[package]
name = "nblfq"
version = "0.1.0"
edition = "2024"

[features]
default = ["std", "tagged_ptr"]
std = ["alloc"]
alloc = []
tagged_ptr = []

[dependencies]
cfg-if = "1.0.3"

[dev-dependencies]
fastrand = "2.3.0"
