[package]
name = "nblf-queue"
version = "0.1.0"
edition = "2024"
description = "Atomic, wait-free MPMC queues based on the nblfq algorithm"
license = "MIT"

[workspace]
members = [
  ".",
  "profiling"
]

[features]
default = ["pool"]
std = ["alloc"]
alloc = []
pool = []
atomic-fallback = ["portable-atomic/fallback"]

[dependencies]
portable-atomic = { version = "1.11.1", default-features = false, features = ["require-cas"] }

[dev-dependencies]
criterion = { version = "0.8.1", features = ["html_reports"] }

[target.'cfg(loom)'.dependencies]
loom = "0.7"

[target.'cfg(shuttle)'.dependencies]
shuttle = "0.8.1"

[target.'cfg(bench_crossbeam)'.dev-dependencies]
crossbeam-queue = "0.3.12"

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(loom)', 'cfg(shuttle)', 'cfg(bench_crossbeam)'] }

[[bench]]
name = "queue_benchmarks"
harness = false
