[package]
name = "nblfq"
version = "0.1.0"
edition = "2024"

[features]
default = ["std", "tagged_ptr"]
std = ["alloc"]
alloc = []
tagged_ptr = []

[dependencies]
cfg-if = "1.0.3"
heapless = {version = "0.9.1", features = ["portable-atomic", "nightly"]}
