[package]
name = "nblf-queue"
version = "0.1.0"
edition = "2024"

[features]
default = ["tagged-ptr", "pool", "alloc"]
std = ["alloc"]
alloc = []
tagged-ptr = []
pool = []

[dependencies]
cfg-if = "1.0.3"
portable-atomic = {version = "1.11.1", default-features = false, features = ["require-cas"] }#["fallback"] }# (for testing AtomicU128)
