[package]
name = "nblf-queue"
version = "0.1.0"
edition = "2024"

[features]
default = ["pool", "alloc", "atomic-fallback"]
std = ["alloc"]
alloc = []
pool = []
atomic-fallback = ["portable-atomic/fallback"]

[dependencies]
cfg-if = "1.0.3"
portable-atomic = {version = "1.11.1", default-features = false, features = ["require-cas"] }
