[project]
name = "nblf-queue"
version = "0.2.0"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.12"
readme = "README.md"
description = "Lock-free, non-blocking MPMC queues."
authors = [
  { name = "Louis Meller", email = "louis.meller@icloud.com" },
]
keywords = ["queue", "mpmc", "atomic", "lock-free"]

[project.urls]
Repository = "https://github.com/lmeller-git/nblf-queue"
Documentation = "https://docs.rs/nblf-queue"

[dependency-groups]
dev = [
  "pytest",
  "pytest-cov",
  "maturin >= 1.9.4",
  "ruff>=0.15.15",
  "pyright>=1.1.410",
  "pytest-benchmark>=5.2.3",
]


[build-system]
requires = ["maturin>=1.9.4"]
build-backend = "maturin"

[tool.maturin]
manifest-path = "bindings/python/Cargo.toml"
module-name = "nblf_queue._nblf_queue_py"
python-source = "python"
profile = "release"

[tool.pytest.ini_options]
norecursedirs = ["target", ".git", ".venv"]
testpaths = ["python/tests"]

[tool.ruff]
cache-dir = ".ruff_cache"
line-length = 100

[tool.ruff.format]
skip-magic-trailing-comma = true

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402"]

[tool.pyright]
include = ["python"]
extraPaths = ["python"]
venvPath = "."
venv = ".venv"
pythonVersion = "3.14"
