name: test CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust Nightly
      run: |
        rustup install nightly
        rustup default nightly

    - name: Install components
      run: rustup component add miri

    - name: Build test bin and run tests
      run: cargo test

    - name: Run miri tests - heapless 
      run: MIRIFLAGS="-Zmiri-ignore-leaks -Zmiri-permissive-provenance" cargo miri test heapless

    - name: RUn miri tests - heap backed
      run: MIRIFLAGS="-Zmiri-permissive-provenance" cargo miri test arrayqueue

